### ISSUE TITLE
Packet Processing Error

### ISSUE THREAD

**Issue by TheCiROMG** [qruet/AnvilLot#13]
**Server Version**
Purpur-1053

**Plugin Version**
3.4_03

**Describe the bug**
[17:33:37 ERROR]: Error whilst processing packet net.minecraft.server.v1_16_R3.PacketPlayInWindowClick@358bf662 for TheCiROMG[/191.84.212.69:21040]
java.lang.NullPointerException: null
        at dev.qruet.anvillot.nms.v1_16_R3.ContainerAnvilLot.updateCost(ContainerAnvilLot.java:264) ~[?:?]
        at dev.qruet.anvillot.nms.IContainerAnvilLot.e(IContainerAnvilLot.java:85) ~[?:?]
        at dev.qruet.anvillot.nms.v1_16_R3.ContainerAnvilLot.e(ContainerAnvilLot.java:251) ~[?:?]
        at dev.qruet.anvillot.nms.v1_16_R3.ContainerAnvilLot.a(ContainerAnvilLot.java:226) ~[?:?]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2816) ~[patched_1.16.5.jar:git-Purpur-1053]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Purpur-1053]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Purpur-1053]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Purpur-1053]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-1053]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-1053]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1053]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-1053]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1326) ~[patched_1.16.5.jar:git-Purpur-1053]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1319) ~[patched_1.16.5.jar:git-Purpur-1053]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-1053]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1295) ~[patched_1.16.5.jar:git-Purpur-1053]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Purpur-1053]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1053]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**To Reproduce**
Putting a set of books on an Anvil and doing so made the player with that error

**Comment by qruet** [comment]
Issue has been resolved, expect a release soon.
