### ISSUE TITLE
some mistake ...

### ISSUE THREAD

**Issue by rkfsociety** [qruet/AnvilLot#15]
This server is running Yatopia version git-Yatopia-ver/1.16.5-114 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Previous version: git-Paper-703 (MC: 1.16.5)

jdk-16.0.1.9-hotspot

[19:47:30] [Server thread/INFO]: [AnvilLot] Enabling AnvilLot v3.4_03-b5
[19:47:30] [Server thread/ERROR]: Error occurred while enabling AnvilLot v3.4_03-b5 (Is it up to date?)
[19:47:30] [Server thread/ERROR]: Suspected Plugins: 
[19:47:30] [Server thread/ERROR]: 	AnvilLot{enabled,ver=3.4_03-b5,path=plugins\AnvilLot.jar}
[19:47:30] [Server thread/ERROR]: Exception details below: 
java.lang.ExceptionInInitializerError: null
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at dev.qruet.anvillot.util.ReflectionUtils.<clinit>(ReflectionUtils.java:20) ~[?:?]
	at dev.qruet.anvillot.util.text.P.<clinit>(P.java:13) ~[?:?]
	at dev.qruet.anvillot.util.text.LanguageLibrary.<clinit>(LanguageLibrary.java:18) ~[?:?]
	at dev.qruet.anvillot.AnvilLot.onEnable(AnvilLot.java:28) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:593) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:303) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessException: module java.base does not open java.lang.reflect to unnamed module @40d2cc67
	at dev.qruet.anvillot.util.jdk1_14.ReflectionUtils.<clinit>(ReflectionUtils.java:33) ~[?:?]
	... 16 more
Caused by: java.lang.IllegalAccessException: module java.base does not open java.lang.reflect to unnamed module @40d2cc67
	at java.lang.invoke.MethodHandles.privateLookupIn(MethodHandles.java:260) ~[?:?]
	at dev.qruet.anvillot.util.jdk1_14.ReflectionUtils.<clinit>(ReflectionUtils.java:30) ~[?:?]
	... 16 more
[19:47:30] [Server thread/INFO]: [AnvilLot] Disabling AnvilLot v3.4_03-b5

**Comment by qruet** [comment]
Dropped support for version dependent ReflectionUtils and found a friendlier approach to field manipulation a while back. Please see next commit that should completely remove those JDK modules from the project entirely.
